site_name: 2026.1_PI1_Grupo1_Lui
site_url: https://fcte-pi1.github.io/2026.1_PI1_Grupo1_Lui/
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast

nav:
  - Home: index.md
  - Manual: manual.md
  - Eletronica:
      - Home: eletronica/index.md
      - Requisitos: eletronica/RequisitosEletronica.md
      - Componentes:
          - Microcontrolador: eletronica/microcontrolador.md
          - Sensores: eletronica/analiseSensores.md
          - Motor: eletronica/Motor.md
  - Energia: 
      - Home: energia/index.md
      - Requisitos: energia/requisitos.md
  - Estruturas: estruturas/index.md
  - Software: 
      - Home: software/index.md
      - Documentação: software/requisitosSoftware.md
      - Avaliação de Tecnologias Front-end: software/avaliacao-tecnologias-frontend.md
